# Generated by Django 6.0.6 on 2026-07-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='engine',
        ),
        migrations.AddField(
            model_name='bike',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='engine_capacity',
            field=models.CharField(default='150cc', max_length=50),
        ),
        migrations.AddField(
            model_name='bike',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bike',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='mileage',
            field=models.CharField(default='45 km/l', max_length=50),
        ),
        migrations.AlterField(
            model_name='bike',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
